na=  input("Digite a primeira tarefa:")
nb=  input("Digite a segunda tarefa:")
nc=  input("Digite a terceira tarefa:")
nd=  input("Digite a quarta tarefa:")
ne=  input("Digite a quinta tarefa:")
nf=  input("Digite a sexta tarefa:")
ng=  input("Digite a sétima tarefa:")
nh=  input("Digite a oitava tarefa:")
ni=  input("Digite a nona tarefa:")
nj=  input("Digite a décima tarefa:")

print(na)
print(nb)
print(nc)
print(nd)
print(ne)
print(nf)
print(ng)
print(nh)
print(ni)
print(nj)